/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Fred Drabble (https://sketchfab.com/FredDrabble)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gaming-room-free-download-1e5aa44bd35d4bd8a07486b61273419c
Title: gaming room FREE DOWNLOAD
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber"; 
import { a } from '@react-spring/three'

import officeScene from '../assets/3d/office.glb'
  

const Office = ({ isRotating, setIsRotating,setCurrentStage, ...props }) => {
    const officeRef = useRef()
  
  
  
    const { gl, viewport } = useThree()
    const { nodes, materials } = useGLTF(officeScene);
  
    const lastX = useRef(0)
    const rotationSpeed = useRef(0)
    const dampingFactor = 0.95

    const handlePointerDown = (e) => {
      e.stopPropagation()
      e.preventDefault()
      setIsRotating(true)

      const clientX = e.touches 
      ? e.touches[0].clientX 
      : e.clientX

      lastX.current = clientX
    }
  
   const handlePointerUp = (e) => {
      e.stopPropagation()
      e.preventDefault()
      setIsRotating(false)
    }

    const handlePointerMove = (e) => {
      e.stopPropagation()
      e.preventDefault()

      if(isRotating) {
        const clientX = e.touches 
      ? e.touches[0].clientX 
      : e.clientX

      const delta = (clientX - lastX.current) /viewport.width 
 
        officeRef.current.rotation.y += delta * 0.01 * Math.PI
        lastX.current = clientX
        rotationSpeed.current = delta * 0.01 * Math.PI
      }
    }

   const handleKeyDown = (e) => {
      if(e.key === 'ArrowLeft'){ 
      if(!isRotating) setIsRotating(true)
      officeRef.current.rotation.y += 0.01 * Math.PI
      rotationSpeed.current = 0.0125
    }  else if(e.key === 'ArrowRight') {
      if(!isRotating) setIsRotating(true)
      officeRef.current.rotation.y -= 0.01 * Math.PI
      rotationSpeed.current = -0.0125
    }
  }

  const handleKeyUp = () => {
    if(e.key === 'ArrowLeft' || e.key === 'ArrowRight'){
       setIsRotating(false)
    }
  }

 useFrame(() => {
   if(!isRotating){
     rotationSpeed.current *= dampingFactor
 
     if(Math.abs(rotationSpeed.current) < 0.001){
       rotationSpeed.current = 0
     }
    officeRef.current.rotation.y += rotationSpeed.current
   } else {
    const rotation = officeRef.current.rotation.y
 

    //   * Normalize the rotation value to ensure it stay within the range [0, 2 *Math.PI]
    //   * The goal is to ensure that the rotation value remains within a specific range to 
    //   * prevent potential issue with large or negative rotation values.
    //   * Here's a step-by-step explanation of what this code does:
    // 1. rotation % (2 * Math.PI) calculates the remainder of the rotation value when divided 
    //    by 2 * Math.PI. This essentially wraps the remainder of the rotation value around once it reaches a 
    //    full circle (360 degrees) so that it stays within the range of 0 to 2 * Math.PI. 
    // 2. (rotation % (2 .* Math.PI) +  Math.PI add 2 * Math.PI to the result from step 1.
    //    This is done to ensure that the value remainders positive and within the range of
    //    0 to 2 * Math.PI even if it was negative after the module operation in step 1. 
    // 3. Finally, {(rotation % (2 * Math.PI) + 2 * Math.PI) % (2 * Math.PI) applies another
    //    module operation to the value obtained in step 2. This step gurantees that the value
    //    always stays within the range of 0 to 2 * Math.PI, which is equivalent to a full
    //    circle in radians.


 const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }

   }
 }) 

useEffect(() => {
  const canvas = gl.domElement
  canvas.addEventListener("pointerdown", handlePointerDown)
  canvas.addEventListener('pointerup', handlePointerUp)
  canvas.addEventListener('pointermove', handlePointerMove)
  document.addEventListener('keyup', handleKeyUp)
  document.addEventListener('keydown', handleKeyDown)
 
  return () => {
    canvas.removeEventListener('pointerdown', handlePointerDown)
    canvas.removeEventListener('pointerup', handlePointerUp)
    canvas.removeEventListener('pointermove', handlePointerMove)
    document.removeEventListener('keyup', handleKeyUp)
    document.removeEventListener('keydown', handleKeyDown)
  }
}, [gl, handlePointerDown, handlePointerUp, handlePointerMove])

    return (
    <a.group ref= {officeRef} {...props}>
      <a.group rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
        <a.group rotation={[Math.PI / 2, 0, 0]}>
          <a.group
            position={[118.568, 25.426, 4.721]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 6]}
          >
            <mesh 
              geometry={nodes["Box002_02_-_Default_0"].geometry}
              material={materials["02_-_Default"]}
            />
            <mesh
              geometry={nodes["Box002_Material_#83_0"].geometry}
              material={materials.Material_83}
            />
            <mesh 
              geometry={nodes["Box002_03_-_Default_0"].geometry}
              material={materials["03_-_Default"]}
            />
            <mesh
              geometry={nodes["Box002_13_-_Default_0"].geometry}
              material={materials["13_-_Default"]}
            />
          </a.group>
          <a.group
            position={[-57.924, 25.426, -27.628]}
            rotation={[-Math.PI / 2, 0, Math.PI / 6]}
          >
            <mesh
              geometry={nodes["Box003_02_-_Default_0"].geometry}
              material={materials["02_-_Default"]}
            />
            <mesh             
              geometry={nodes["Box003_Material_#83_0"].geometry}
              material={materials.Material_83}
            />
            <mesh             
              geometry={nodes["Box003_03_-_Default_0"].geometry}
              material={materials["03_-_Default"]}
            />
            <mesh  
              geometry={nodes["Box003_13_-_Default_0"].geometry}
              material={materials["13_-_Default"]}
            />
          </a.group>
          <a.group
            position={[139.8, 0, 27.333]}
            rotation={[-Math.PI / 2, 0, 1.134]}
          >
            <mesh  
              geometry={nodes["Cylinder010_02_-_Default_0"].geometry}
              material={materials["02_-_Default_0"]}
            />
            <mesh  
              geometry={nodes["Cylinder010_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
          </a.group>
          <a.group
            position={[146.046, 33.129, 14.355]}
            rotation={[0, -0.436, Math.PI / 2]}
            scale={[0.674, 0.674, 0.896]}
          >
            <mesh 
              geometry={nodes["Cylinder012_02_-_Default_0"].geometry}
              material={materials["02_-_Default_0"]}
            />
            <mesh   
              geometry={nodes["Cylinder012_Material_#26_0"].geometry}
              material={materials.Material_26}
            />
          </a.group>
          <a.group
            position={[34.615, 25.426, -35.321]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh 
              geometry={nodes["Box004_02_-_Default_0"].geometry}
              material={materials["02_-_Default"]}
            />
            <mesh
              geometry={nodes["Box004_Material_#83_0"].geometry}
              material={materials.Material_83}
            />
            <mesh 
              geometry={nodes["Box004_03_-_Default_0"].geometry}
              material={materials["03_-_Default"]}
            />
            <mesh 
              geometry={nodes["Box004_13_-_Default_0"].geometry}
              material={materials["13_-_Default"]}
            />
          </a.group>
          <a.group
            position={[-135.652, 0, 28.517]}
            rotation={[-Math.PI / 2, 0, 2.007]}
          >
            <mesh     
              geometry={nodes["Cylinder016_02_-_Default_0"].geometry}
              material={materials["02_-_Default_0"]}
            />
            <mesh  
              geometry={nodes["Cylinder016_07_-_Default_0"].geometry}
              material={materials["07_-_Default"]}
            />
          </a.group>
          <a.group
            position={[-141.578, 33.129, 15.39]}
            rotation={[0, 0.436, Math.PI / 2]}
            scale={[0.674, 0.674, 0.896]}
          >
            <mesh   
              geometry={nodes["Cylinder018_02_-_Default_0"].geometry}
              material={materials["02_-_Default_0"]}
            />
            <mesh   
              geometry={nodes["Cylinder018_Material_#26_0"].geometry}
              material={materials.Material_26}
            />
          </a.group>
          <a.group
            position={[47.82, -0.996, 69.998]}
            rotation={[-Math.PI / 2, 0, 1.658]}
            scale={0.21}
          >
            <mesh   
              geometry={nodes["Box001_01_-_Default_0"].geometry}
              material={materials["01_-_Default"]}
            />
            <mesh   
              geometry={nodes["Box001_13_-_Default_0"].geometry}
              material={materials["13_-_Default_0"]}
            />
            <mesh 
              geometry={nodes["Box001_02_-_Default_0"].geometry}
              material={materials["02_-_Default_1"]}
            />
            <mesh 
              geometry={nodes["Box001_03_-_Default_0"].geometry}
              material={materials["03_-_Default_0"]}
            />
            <mesh
              geometry={nodes["Box001_07_-_Default_0"].geometry}
              material={materials["07_-_Default_0"]}
            />
            <mesh   
              geometry={nodes["Box001_07_-_Default_0_1"].geometry}
              material={materials["07_-_Default_1"]}
            />
          </a.group>
          <a.group position={[0.184, 0, 65.626]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh    
              geometry={nodes["Box005_15_-_Default_0"].geometry}
              material={materials["15_-_Default"]}
            />
            <mesh 
              geometry={nodes["Box005_14_-_Default_0"].geometry}
              material={materials["14_-_Default"]}
            />
          </a.group>
          <a.group
            position={[5.839, -7.659, 7.98]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 0.627, 0.36]}
          >
            <mesh 
              geometry={nodes["Box006_Material_#195_0"].geometry}
              material={materials.Material_195}
            />
            <mesh
              geometry={nodes["Box006_07_-_Default_0"].geometry}
              material={materials["07_-_Default_0"]}
            />
          </a.group>
          <a.group
            position={[-9.657, 4.698, 65.836]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <a.group position={[0.019, 1.129, -124.145]}>
              <mesh
                geometry={nodes["Box008_15_-_Default_0"].geometry}
                material={materials["15_-_Default"]}
              />
              <mesh
                geometry={nodes["Box008_07_-_Default_0"].geometry}
                material={materials["07_-_Default_0"]}
              />
            </a.group>
          </a.group>
          <a.group
            position={[197.282, 6.558, -4.408]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.699, 0.929, 0.674]}
          >
            <mesh 
              geometry={nodes["Box011_20_-_Default_0"].geometry}
              material={materials["20_-_Default"]}
            />
            <mesh
              geometry={nodes["Box011_07_-_Default_0"].geometry}
              material={materials["07_-_Default_0"]}
            />
            <mesh 
              geometry={nodes["Box011_22_-_Default_0"].geometry}
              material={materials["22_-_Default"]}
            />
          </a.group>
          <a.group
            position={[-213.999, -148.217, -26.102]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.365, 0.365, 0.621]}
          >
            <mesh 
              geometry={nodes["Cylinder020_11_-_Default_0"].geometry}
              material={materials["11_-_Default"]}
            />
            <mesh 
              geometry={nodes["Cylinder020_10_-_Default_0"].geometry}
              material={materials["10_-_Default"]}
            />
          </a.group>
          <a.group position={[4.83, 75.116, -98.405]} scale={0.721}>
            <mesh
              geometry={nodes["Plane002_Material_#264_0"].geometry}
              material={materials.Material_264}
            />
            <mesh 
              geometry={nodes["Plane002_Material_#333_0"].geometry}
              material={materials.Material_333}
            />
            <mesh
              geometry={nodes["Plane002_Material_#195_0"].geometry}
              material={materials.Material_195}
            />
          </a.group>
          <a.group
            position={[261.168, 75.116, 156.393]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={0.721}
          >
            <mesh 
              geometry={nodes["Plane003_Material_#264_0"].geometry}
              material={materials.Material_264}
            />
            <mesh
              geometry={nodes["Plane003_18_-_Default_0"].geometry}
              material={materials["18_-_Default"]}
            />
            <mesh 
              geometry={nodes["Plane003_Material_#195_0"].geometry}
              material={materials.Material_195}
            />
            <mesh
              geometry={nodes["Plane003_22_-_Default_0"].geometry}
              material={materials["22_-_Default"]}
            />
          </a.group>
          <a.group
            position={[-138.019, 0, 988.666]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              geometry={nodes["Box015_21_-_Default_0"].geometry}
              material={materials["21_-_Default"]}
            />
            <mesh 
              geometry={nodes["Box015_Material_#299_0"].geometry}
              material={materials.Material_299}
            />
            <mesh 
              geometry={nodes["Box015_Material_#304_0"].geometry}
              material={materials.Material_304}
            />
            <mesh
              geometry={nodes["Box015_Material_#301_0"].geometry}
              material={materials.Material_301}
            />
            <mesh
              geometry={nodes["Box015_24_-_Default_0"].geometry}
              material={materials["24_-_Default"]}
            />
          </a.group>
          <mesh 
            geometry={nodes["Cylinder011_02_-_Default_0"].geometry}
            material={materials["02_-_Default_0"]}
            position={[146.179, 0, 3.45]}
            rotation={[-Math.PI / 2, 0, 1.134]}
          />
          <mesh
            geometry={nodes["GeoSphere004_02_-_Default_0"].geometry}
            material={materials["02_-_Default_0"]}
            position={[131.503, 33.12, 45.508]}
            rotation={[-Math.PI / 2, 0, 1.134]}
            scale={0.92}
          />
          <mesh  
            geometry={nodes["Cylinder014_02_-_Default_0"].geometry}
            material={materials["02_-_Default_0"]}
            position={[141.583, 1.43, 35.627]}
            rotation={[-Math.PI / 2, 0, 1.134]}
            scale={[0.57, 0.57, 1.222]}
          />
          <mesh 
            geometry={nodes["Cylinder015_02_-_Default_0"].geometry}
            material={materials["02_-_Default_0"]}
            position={[132.381, 1.43, 31.335]}
            rotation={[-Math.PI / 2, 0, 1.134]}
            scale={[0.57, 0.57, 1.222]}
          />
          <mesh  
            geometry={nodes["Cylinder017_02_-_Default_0"].geometry}
            material={materials["02_-_Default_0"]}
            position={[-149.847, 0, 8.278]}
            rotation={[-Math.PI / 2, 0, 2.007]}
          />
          <mesh 
            geometry={nodes["GeoSphere005_02_-_Default_0"].geometry}
            material={materials["02_-_Default_0"]}
            position={[-127.062, 33.12, 46.555]}
            rotation={[-Math.PI / 2, 0, 2.007]}
            scale={0.92}
          />
          <mesh
            geometry={nodes["Box009_Material_#195_0"].geometry}
            material={materials.Material_195}
            position={[197.282, -151.061, -4.408]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1.191, 1]}
          />
          <mesh
            geometry={nodes["Box010_Material_#195_0"].geometry}
            material={materials.Material_195}
            position={[-185.543, -151.061, -4.408]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1.191, 1]}
          />
          <mesh 
            geometry={nodes["Box012_05_-_Default_0"].geometry}
            material={materials["05_-_Default"]}
            position={[-218.607, -47.433, 11.084]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.517, 1, 1]}
          />
          <mesh  
            geometry={nodes["Box013_04_-_Default_0"].geometry}
            material={materials["04_-_Default"]}
            position={[-194.114, -47.433, 18.7]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.517, 1, 1]}
          />
          <mesh 
            geometry={nodes["Box014_05_-_Default_0"].geometry}
            material={materials["05_-_Default"]}
            position={[-162.355, -49.417, 9.475]}
            rotation={[Math.PI / 2, 1.396, -Math.PI]}
            scale={[0.44, 1, 0.596]}
          />
          <mesh
            geometry={nodes["Cylinder019_Material_#263_0"].geometry}
            material={materials.Material_263}
            position={[-213.633, -145.673, -25.923]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh 
            geometry={nodes["Cylinder021_24_-_Default_0"].geometry}
            material={materials["24_-_Default"]}
            position={[-108.158, -150.898, -32.593]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh 
            geometry={nodes["Plane001_Material_#413_0"].geometry}
            material={materials.Material_413}
            position={[6.27, -151.247, 154.387]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.721, 0.807, 0.721]}
          />
        </a.group>
      </a.group>
    </a.group>
  );
}

export default Office